package com.example.myapplication.models

import com.google.gson.annotations.SerializedName

data class DetailResep(
    @SerializedName("strMeal") val namaMakanan : String?,
    @SerializedName("strCategory") val categoryMakanan : String?,
    @SerializedName("strInstructions") val perintah : String?,
    @SerializedName("strMealThumb") val gambarMakanan : String?,
    @SerializedName("strYoutube") val linkYoutube : String?,
    @SerializedName("strIngredient1") val gradient1 : String?,
    @SerializedName("strIngredient2") val gradient2 : String?,
    @SerializedName("strIngredient3") val gradient3 : String?,
    @SerializedName("strIngredient4") val gradient4 : String?,
    @SerializedName("strIngredient5") val gradient5 : String?,
    @SerializedName("strIngredient6") val gradient6 : String?,
    @SerializedName("strIngredient7") val gradient7 : String?,
    @SerializedName("strIngredient8") val gradient8 : String?,
    @SerializedName("strIngredient9") val gradient9 : String?,
    @SerializedName("strIngredient10") val gradient10 : String?,
    @SerializedName("strIngredient11") val gradient11 : String?,
    @SerializedName("strIngredient12") val gradient12 : String?,
    @SerializedName("strIngredient13") val gradient13 : String?,
    @SerializedName("strIngredient14") val gradient14 : String?,
    @SerializedName("strIngredient15") val gradient15 : String?,
    @SerializedName("strIngredient16") val gradient16 : String?,
    @SerializedName("strIngredient17") val gradient17 : String?,
    @SerializedName("strIngredient18") val gradient18 : String?,
    @SerializedName("strIngredient19") val gradient19 : String?,
    @SerializedName("strIngredient20") val gradient20 : String?,
    @SerializedName("strMeasure1") val jumlah1 : String?,
    @SerializedName("strMeasure2") val jumlah2 : String?,
    @SerializedName("strMeasure3") val jumlah3 : String?,
    @SerializedName("strMeasure4") val jumlah4 : String?,
    @SerializedName("strMeasure5") val jumlah5 : String?,
    @SerializedName("strMeasure6") val jumlah6 : String?,
    @SerializedName("strMeasure7") val jumlah7 : String?,
    @SerializedName("strMeasure8") val jumlah8 : String?,
    @SerializedName("strMeasure9") val jumlah9 : String?,
    @SerializedName("strMeasure10") val jumlah10 : String?,
    @SerializedName("strMeasure11") val jumlah11 : String?,
    @SerializedName("strMeasure12") val jumlah12 : String?,
    @SerializedName("strMeasure13") val jumlah13 : String?,
    @SerializedName("strMeasure14") val jumlah14 : String?,
    @SerializedName("strMeasure15") val jumlah15 : String?,
    @SerializedName("strMeasure16") val jumlah16 : String?,
    @SerializedName("strMeasure17") val jumlah17 : String?,
    @SerializedName("strMeasure18") val jumlah18 : String?,
    @SerializedName("strMeasure19") val jumlah19 : String?,
    @SerializedName("strMeasure20") val jumlah20 : String?,

)
